docs: update readme
Badger-Finance/badger-multisig pull request #1475
Opened 2023-12-21 23:25 UTC by sajanrajdev

Minor updates to the docs

2024-01-03 09:26 UTC, petrovska-petro approved these changes
written updates informs better of latest shape of diff msigs and their scope, removed one signer from techops scope ✅

2024-01-03 21:31 UTC, ICEBADGER requested changes
I think there is an extra "s" in line 83 after "required"

Otherwise looks good.

2024-01-18 00:05 UTC, ICEBADGER approved these changes

2024-01-18 10:10 UTC, petrovska-petro approved these changes

2024-01-19 11:26 UTC, merged