Add migration script across bridge to hub pool
Badger-Finance/badger-multisig pull request #451
Opened 2022-05-16 13:48 UTC by petrovska-petro

Tackles #439 

```
brownie run issue/439/migrate_liq_across_v2
```

2022-05-16 14:32 UTC, jorijnsmit commented on scripts/issue/439/migrate_liq_across_v2.py
> +    )
this is not very pythonic/readable. had to decypher it a bit:
```
if a_badger_lp_balance > lp_withdraw_mantisa:
    lp_withdraw_mantisa = lp_withdraw_mantisa
else:
    lp_withdraw_mantisa = a_badger_lp_balance
```
or
```
if a_badger_lp_balance < lp_withdraw_mantisa:
    lp_withdraw_mantisa = a_badger_lp_balance
```
or
```
lp_withdraw_mantisa = min(a_badger_lp_balance, lp_withdraw_mantisa)
```

2022-05-19 10:00 UTC, jorijnsmit requested changes

2022-05-19 10:59 UTC, petrovska-petro commented on scripts/issue/439/migrate_liq_across_v2.py
> +    a_badger_lp = safe.contract(registry.eth.treasury_tokens.aBADGER)
added the interface in last commits, nasty interface errors 💀

2022-05-19 11:02 UTC, jorijnsmit approved these changes

2022-05-23 15:50 UTC, jalbrekt85 approved these changes

2022-05-23 23:11 UTC, merged